### PR TITLE
Fixed #22 - Added methods to return all possible events (get_events), as...

### PR DESCRIPTION
**Pull request by julianpistorius**
... well as valid next events given current state (get_next_event_names)

### CODE REVIEW

**Comment by kageurufu** [comment]
Only thing I would want is something like get_next_events that returns a dict of name: func, so we dont have to use the getattr method

**Comment by julianpistorius** [comment]
True. That would be useful. I'll add that.

**Comment by julianpistorius** [comment]
@kageurufu How's that?

**Comment by kageurufu** [comment]
:+1: looks good

**Pull request merged**
